### ISSUE TITLE
Continuously restarting

### ISSUE THREAD

**Issue by Toontje** [jfjallid/docker-ntp-server#1]
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                         PORTS                                                                                                                                            NAMES
0372d2703e15        jfjallid/ntp-server             "/usr/sbin/chronyd..."   15 minutes ago      Restarting (1) 6 minutes ago                                                                                                                                                    ntp-server
```
Docker version 17.03.1-ce, build c6d412e
Linux ubuntu 4.8.0-56-generic #61~16.04.1-Ubuntu SMP Wed Jun 14 11:58:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jfjallid** [comment]
Yes, I have noticed this issue too and if it is the same problem it is due to the pid file not being removed.

**Comment by jfjallid** [comment]
@Toontje This should now be resolved in 60df4dc3bbff10098fbdfdfce0c5e96caa286c10

**Comment by hanscees** [comment]
hi, 
it still keeps restarting. Should we put the chrony.sh in the local directory or something?

**Comment by jfjallid** [comment]
@hanscees If you cloned this repo chrony.sh should already be in the same directory as the Dockerfile and thus automatically be copied inside the container when you build the image.
