### ISSUE TITLE
using docker-compose

### ISSUE THREAD

**Issue by hanscees** [jfjallid/docker-ntp-server#2]
When using docker-compose the dockerfile does not work: complains about chronyd.sh not found in path and later no rights.

I have solved this like so:

###################### docker-compose.yml
version: '2'

services:
  ntp:
    build: .
    restart: always
    privileged: true
    container_name: ntp
    ports:
      - "123:123/udp"
    volumes:
      - ntp_conf:/var/lib/chrony

volumes:
  ntp_conf:

#######################
#Dockerfile
FROM alpine:3.3
MAINTAINER Jimmy Fjällid <jimmy@fjallid.com>

RUN apk add --no-cache \
        bash \
        coreutils \
        curl \
        chrony \
        vim
COPY chronyd.sh /usr/bin/
RUN chmod +x /usr/bin/chronyd.sh

ENTRYPOINT ["/usr/bin/chronyd.sh"]
#######################################3

Seems to work now

**Comment by jfjallid** [comment]
I'm sorry for the late response, but I'm glad that you found the solution by yourself! 
I've updated the Dockerfile to use an absolute path instead for the Entrypoint command, and to mark the script as executable.
